name: Python application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "oumaimanijaoui" --password-stdin
        docker image build -t dab8106/python:latest .
       
    - name: Push 
      run: |
         docker tag dab8106/python:latest oumaimanijaoui:newww
         docker push ${{secrets.DOCKER_USER}}  oumaimanijaoui:newww